// Generated by CoffeeScript 1.9.3
(function() {
  var CommentBox, FileList, Page, RenderedCommentBox, d;

  d = React.DOM;

  FileList = React.createFactory(React.createClass({
    getInitialState: function() {
      return {
        fileList: [],
        createFile: _.debounce(this.createFile, 500, true)
      };
    },
    componentDidMount: function() {
      return this.props.dbClient.authenticate((function(_this) {
        return function(error, data) {
          return _this.props.dbClient.readdir("/", function(error, entries) {
            if (error) {
              console.log(error);
              return;
            }
            return _this.setState({
              fileList: entries
            });
          });
        };
      })(this));
    },
    createFile: function() {
      var fileName, now;
      now = (new Date()).toISOString().replace(/:/g, ".");
      fileName = now + ".txt";
      return this.props.dbClient.authenticate((function(_this) {
        return function(error, data) {
          return _this.props.dbClient.writeFile(fileName, " ", function(error, stat) {
            var currentFileList;
            console.log(fileName);
            currentFileList = _this.state.fileList;
            currentFileList.push(fileName);
            _this.props.onSelect(fileName);
            return _this.setState(currentFileList);
          });
        };
      })(this));
    },
    render: function() {
      return d.ul({
        className: "list-group"
      }, d.li({
        className: "list-group-item",
        onClick: this.state.createFile
      }, "Create New Entry"), this.state.fileList.map((function(_this) {
        return function(entry, i) {
          return d.li({
            className: "list-group-item",
            key: i,
            onClick: function() {
              return _this.props.onSelect(entry);
            }
          }, entry);
        };
      })(this)));
    }
  }));

  RenderedCommentBox = React.createFactory(React.createClass({
    render: function() {
      var raw_markup;
      raw_markup = marked(this.props.comment, {
        sanitize: true
      });
      return d.div({}, d.span({
        dangerouslySetInnerHTML: {
          __html: raw_markup
        }
      }));
    }
  }));

  CommentBox = React.createFactory(React.createClass({
    getInitialState: function() {
      return {
        uploader: _.throttle(this.uploadToDropbox, 5000),
        comment: "",
        geolocation: null,
        userInfo: {},
        lastUpdated: ""
      };
    },
    getDefaultProps: function() {
      return {
        fileToLoad: ""
      };
    },
    componentDidMount: function() {
      return this.props.dbClient.authenticate((function(_this) {
        return function(error, data) {
          if (error) {
            console.log(error);
          }
          _this.props.dbClient.getAccountInfo(function(error, userInfo) {
            return _this.setState({
              userInfo: userInfo
            });
          });
          if (_this.props.fileToLoad) {
            console.log("did mount filetoload", _this.props.fileToLoad);
            return _this.props.dbClient.readFile(_this.props.fileToLoad, function(error, data) {
              return _this.setState({
                comment: data
              }, function() {
                return _this.props.setCompiledComment(_this.compileText());
              });
            });
          }
        };
      })(this));
    },
    componentWillReceiveProps: function(nextProps) {
      console.log("nextProps", nextProps.fileToLoad);
      if (nextProps.fileToLoad !== this.props.fileToLoad) {
        console.log("should be loading new file");
        return this.props.dbClient.authenticate((function(_this) {
          return function(error, data) {
            return _this.props.dbClient.readFile(nextProps.fileToLoad, function(error, data) {
              return _this.setState({
                comment: data
              }, function() {
                return _this.props.setCompiledComment(_this.compileText());
              });
            });
          };
        })(this));
      }
    },
    compileText: function() {
      var to_ret;
      to_ret = "";
      if (this.state.geolocation) {
        to_ret = "Location: " + this.state.geolocation.latitude + ", " + this.state.geolocation.longitude;
      }
      to_ret = to_ret + "\n\n" + this.state.comment;
      return to_ret;
    },
    uploadToDropbox: function() {
      console.log("uploadToDropbox");
      return this.props.dbClient.writeFile(this.props.fileToLoad, this.compileText(), (function(_this) {
        return function(error, stat) {
          if (error) {
            console.log(error);
          }
          return _this.setState({
            lastUpdated: stat.modifiedAt
          });
        };
      })(this));
    },
    getLocation: function() {
      if (navigator.geolocation) {
        return navigator.geolocation.getCurrentPosition((function(_this) {
          return function(position) {
            console.log(position.coords);
            return _this.setState({
              geolocation: {
                latitude: position.coords.latitude,
                longitude: position.coords.longitude
              }
            });
          };
        })(this));
      }
    },
    handleChange: function(e) {
      this.setState({
        comment: e.target.value
      }, (function(_this) {
        return function() {
          return _this.props.setCompiledComment(_this.compileText());
        };
      })(this));
      return this.state.uploader();
    },
    render: function() {
      return d.div({}, d.div({}, d.p({}, "Hello " + this.state.userInfo.name), d.textarea({
        cols: 80,
        rows: 20,
        onChange: this.handleChange,
        value: this.state.comment
      }), d.p({}, "Last Updated: " + this.state.lastUpdated)));
    }
  }));

  Page = React.createClass({
    getInitialState: function() {
      return {
        currentFile: "",
        compiledComment: ""
      };
    },
    onSelect: function(file) {
      console.log("onselect", file);
      return this.setState({
        currentFile: file
      });
    },
    setCompiledComment: function(comment) {
      return this.setState({
        compiledComment: comment
      });
    },
    render: function() {
      return d.div({
        className: "row"
      }, d.div({
        className: "col-md-2"
      }, FileList({
        dbClient: this.props.dbClient,
        onSelect: this.onSelect
      })), d.div({
        className: "col-md-5"
      }, this.state.currentFile ? CommentBox({
        fileToLoad: this.state.currentFile,
        dbClient: this.props.dbClient,
        setCompiledComment: this.setCompiledComment
      }) : void 0), d.div({
        className: "col-md-5"
      }, RenderedCommentBox({
        comment: this.state.compiledComment
      })));
    }
  });

  $(function() {
    var client, element;
    client = new Dropbox.Client({
      key: "r8bf46heo7t3ley"
    });
    element = React.createElement(Page, {
      dbClient: client
    }, null);
    return React.render(element, document.getElementById('react'));
  });

}).call(this);
